/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrameVisual;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import controle.controleEspaco;


public class registrarEspaco extends javax.swing.JFrame {
    private controleEspaco controle;
    private listaEspacos atttabela;
    private telaInicial atttabela2;

    public registrarEspaco(listaEspacos atttabela) {
        this.atttabela = atttabela;
        controle = new controleEspaco();
        initComponents();
        inicializarComponentes();
    }
    public registrarEspaco(telaInicial atttabela2) {
        this.atttabela2 = atttabela2;
        controle = new controleEspaco();
        initComponents();
        inicializarComponentes();
    }
    public registrarEspaco(listaEspacos atttabela, int idEspaco) {
        controle = new controleEspaco();
        this.atttabela = atttabela;
        controle.carregarEspaco(idEspaco);
        controle.setEditarRegistro(true);
        initComponents();
        inicializarComponentes();
        setarDados();
        
    }

    public void inicializarComponentes() {
        DefaultComboBoxModel<Integer> model = new DefaultComboBoxModel<Integer>(controle.exibirLocalizacao());
        jComboBox1LOCALIZACAO.setModel(model);
    }

    public void setarDados() {
        jTextField1METROS_QUADRADOS.setText(""+controle.getEspaco().getMetros_quadrados());
        jComboBox3KIOSQUE_LOJA.setSelectedItem(controle.getEspaco().getKiosque_loja());
        jComboBox1LOCALIZACAO.setSelectedItem(controle.getEspaco().getLocalizacao().getId());


    }
    public void limparDados() {
        jTextField1METROS_QUADRADOS.setText("");
        jComboBox3KIOSQUE_LOJA.setSelectedItem(null);
        jComboBox1LOCALIZACAO.setSelectedItem(null);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1METROS_QUADRADOS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1LOCALIZACAO = new javax.swing.JComboBox<>();
        jComboBox3KIOSQUE_LOJA = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        jLabel1.setText("REGISTRO DE ESPAÇO");

        jLabel2.setText("metros quadrados");

        jLabel7.setText("localização");

        //jComboBox1LOCALIZACAO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3KIOSQUE_LOJA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kiosque", "Loja" }));

        jLabel9.setText("tipo de espaço");

        jButton1OK.setText("OK");
        jButton1OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1LOCALIZACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox3KIOSQUE_LOJA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1METROS_QUADRADOS, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton1OK)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1METROS_QUADRADOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3KIOSQUE_LOJA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1LOCALIZACAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton1OK)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jButton1OKActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            String metrosQuadrados = jTextField1METROS_QUADRADOS.getText();
            String kiosqueLoja = jComboBox3KIOSQUE_LOJA.getSelectedItem().toString();

            if(kiosqueLoja.equalsIgnoreCase("Kiosque")) {
                controle.getEspaco().setKiosque_loja(false);
            } else {
                controle.getEspaco().setKiosque_loja(true);
            }

            controle.getEspaco().setMetros_quadrados(Double.parseDouble(metrosQuadrados));

            int posicao = jComboBox1LOCALIZACAO.getSelectedIndex();
            controle.getEspaco().setLocalizacao(controle.getListarlocais().get(posicao));

            Boolean estado = false;
            controle.getEspaco().setEstado_alugado(estado);



            if(controle.salvar()) {
                setVisible(true);
                int retorno =
                JOptionPane.showConfirmDialog(null, "Espaço registrado com sucesso !" +
                "você deseja registar um novo espaço ?", "Opções", JOptionPane.YES_NO_OPTION);
                if(retorno ==0) {
                    limparDados();
                } else {
                    setVisible(false);
                }

                if(atttabela != null) {
                    atttabela.atualizarTabela();
                }
            } 
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "falha ao registar locaolização\n" + e.getMessage(),
        "ERRO 44LL", JOptionPane.ERROR_MESSAGE);
        }
        
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarEspaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarEspaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarEspaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarEspaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1OK;
    private javax.swing.JComboBox<Integer> jComboBox1LOCALIZACAO;
    private javax.swing.JComboBox<String> jComboBox3KIOSQUE_LOJA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1METROS_QUADRADOS;
    // End of variables declaration                   
}
