/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrameVisual;
import controle.Tecladinho;
import controle.controleFolha_aluguel;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class registrarDIVIDA extends javax.swing.JFrame {
    
    private controleFolha_aluguel controle;
    private listaFolha_pagamento atttabela;
    private telaInicial atttabela2;
    private Double valorMinimo;
    private boolean humanoVSmaquina = false;

    public registrarDIVIDA(listaFolha_pagamento atttabela) {
        this.atttabela = atttabela;
        controle = new controleFolha_aluguel();
        initComponents();
        setLocationRelativeTo(null);
        inicializarComponentes();
    }
    public registrarDIVIDA(telaInicial atttabela2) {
        this.atttabela2 = atttabela2;
        controle = new controleFolha_aluguel();
        initComponents();
        setLocationRelativeTo(null);
        inicializarComponentes();
    }
    public registrarDIVIDA(listaFolha_pagamento atttabela, int idDivida) { //EDITAR DIVIDA 🎈
        controle = new controleFolha_aluguel();
        this.atttabela = atttabela;
        controle.carregarDivida(idDivida);
        controle.setEditarRegistro(true);
        initComponents();
        setLocationRelativeTo(null);
        inicializarComponentes();
        setarDados();
    }
    public void inicializarComponentes() {
        DefaultComboBoxModel<Integer> model = new DefaultComboBoxModel<Integer>(controle.exibirContratos());
        jComboBox1ID_CONTRATO.setModel(model);
    }
    public void setarDados() {
        jTextField1VALOR.setText(""+controle.getFolha_aluguel().getValor());
        jTextField2DESCRICAO.setText(controle.getFolha_aluguel().getDescricao());
        jTextField3NUMERO_PARCELA.setText(""+controle.getFolha_aluguel().getNumero_parcela());
        jTextField4DATA_VENCIMENTO.setText(Tecladinho.getDateFormat().format(controle.getFolha_aluguel().getData_vencimento()));
        jComboBox1ID_CONTRATO.setSelectedItem(controle.getFolha_aluguel().getContrato().getId());

    }
    public void limparDados() {
        jTextField1VALOR.setText("");
        jTextField2DESCRICAO.setText("");
        jTextField3NUMERO_PARCELA.setText("");
        jTextField4DATA_VENCIMENTO.setText("");
        jComboBox1ID_CONTRATO.setSelectedIndex(1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1VALOR = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2DESCRICAO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4DATA_VENCIMENTO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1ID_CONTRATO = new javax.swing.JComboBox<>();
        jButton1OK = new javax.swing.JButton();
        jTextField3NUMERO_PARCELA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 17)); // NOI18N
        jLabel1.setText("REGISTRO DE DIVIDA");

        jLabel2.setText("valor");

        jTextField1VALOR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1VALORFocusLost(evt);
            }
        });

        jLabel3.setText("descrição");

        jLabel4.setText("numero da parcela");

        jLabel5.setText("data de vencimento");

        jLabel7.setText("ID do contrato");

        //jComboBox1ID_CONTRATO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1ID_CONTRATO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ID_CONTRATOActionPerformed(evt);
            }
        });

        jButton1OK.setText("OK");
        jButton1OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1ID_CONTRATO, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(jButton1OK))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField1VALOR, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2DESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(107, 107, 107)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3NUMERO_PARCELA, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4DATA_VENCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1ID_CONTRATO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1VALOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2DESCRICAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4DATA_VENCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jButton1OK)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3NUMERO_PARCELA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jButton1OKActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            String valor = jTextField1VALOR.getText();
            String descricao = jTextField2DESCRICAO.getText();
            String numeroParcela = jTextField3NUMERO_PARCELA.getText();
            String dataVencimento = jTextField4DATA_VENCIMENTO.getText();

            controle.getFolha_aluguel().setValor(Double.parseDouble(valor));

            Boolean estado = false;
            controle.getFolha_aluguel().setFoi_pago(estado);

            controle.getFolha_aluguel().setDescricao(descricao);
            controle.getFolha_aluguel().setNumero_parcela(Integer.parseInt(numeroParcela));
            controle.getFolha_aluguel().setData_vencimento(Tecladinho.getDateFormat().parse(dataVencimento));

            int posicao = jComboBox1ID_CONTRATO.getSelectedIndex();

            


            if(posicao <= 0) { // para verificar se algum contrato foi selecionado
                JOptionPane.showMessageDialog(null, "por favor selecione um contrato\n",
        "ERRO 99rr", JOptionPane.ERROR_MESSAGE);
                return;
            }

            controle.getFolha_aluguel().setContrato(controle.getListarContratos().get(posicao-1));


            if(Double.parseDouble(valor) < valorMinimo) { // para verificar se a parcela tem o valor minimo
                JOptionPane.showMessageDialog(null, "o valor minimo da parcela é de \n" + valorMinimo + " Reais",
                "erro qq33", JOptionPane.INFORMATION_MESSAGE);
                return;
            }


            if(controle.salvar()) { // para salvar o contrato
                setVisible(true);
                int retorno =
                JOptionPane.showConfirmDialog(null, "Divida registrada com sucesso ! \n" +
                "você deseja registar uma nova divida ?", "Opções", JOptionPane.YES_NO_OPTION);
                if(retorno ==0) {
                    limparDados();
                } else {
                    setVisible(false);
                }

                if (atttabela != null) {
                    atttabela.atualizarTabela();
                }
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "falha ao registar divida\n" + e.getMessage(),
        "ERRO 22qq", JOptionPane.ERROR_MESSAGE);
        }
    }                                          

    private void jComboBox1ID_CONTRATOActionPerformed(java.awt.event.ActionEvent evt) {    


        if (controle.isEditarRegistro() == false && humanoVSmaquina == false) {
            int posicao = jComboBox1ID_CONTRATO.getSelectedIndex();
         
         
        valorMinimo = controle.getListarContratos().get(posicao-1).getValor_alugel();
        jTextField1VALOR.setText(""+valorMinimo);
        }                                                  
    }     
    
    private void jTextField1VALORFocusLost(java.awt.event.FocusEvent evt) {                                           
       humanoVSmaquina = true;

    }   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarDIVIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarDIVIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarDIVIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarDIVIDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1OK;
    private javax.swing.JComboBox<Integer> jComboBox1ID_CONTRATO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1VALOR;
    private javax.swing.JTextField jTextField2DESCRICAO;
    private javax.swing.JTextField jTextField3NUMERO_PARCELA;
    private javax.swing.JTextField jTextField4DATA_VENCIMENTO;
    // End of variables declaration                   
}
